#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Linting and formating your project before committing'

npm run lint

# If everything passes... Now we can commit

npx lint-staged

echo '✅✅✅✅ I am committing this now. ✅✅✅✅'